insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Emmerich and Sons', 16333, 1592, 1);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Adams-Lowe', 19740, 2067, 2);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Abernathy LLC', 10525, 2454, 3);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Weimann, Yost and Schamberger', 21779, 450, 4);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Yundt Group', 7846, 2082, 5);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Shanahan LLC', 12198, 657, 6);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Pacocha, Keebler and Davis', 6516, 1140, 7);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Reynolds, Turcotte and Hackett', 2920, 307, 8);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Batz, Hickle and Auer', 3816, 402, 9);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('O''Hara Inc', 2390, 1375, 10);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Wolf, Lueilwitz and Sawayn', 2262, 2006, 11);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Jacobi, Runolfsson and Hyatt', 10621, 67, 12);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Stanton-Watsica', 20446, 1751, 13);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Kunze and Sons', 11127, 281, 14);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Kling Group', 24250, 2013, 15);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Thiel and Sons', 6130, 2473, 16);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Kshlerin-Lynch', 16623, 1073, 17);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Stark Group', 19282, 871, 18);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Rolfson, Braun and Abbott', 20756, 357, 19);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Toy-Osinski', 56, 1599, 20);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Marquardt, Kreiger and Torphy', 7757, 1226, 21);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Weber, Schulist and Lowe', 22636, 750, 22);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Stokes, Fisher and Bartoletti', 17871, 170, 23);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Rowe, Walker and Okuneva', 4111, 530, 24);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Erdman, Green and Casper', 5715, 262, 25);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Reichel Group', 24924, 125, 26);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('West-O''Conner', 13365, 251, 27);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Bailey, Skiles and Little', 23974, 1486, 28);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('O''Kon-Rippin', 9448, 964, 29);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('King, Satterfield and Nolan', 18013, 1146, 30);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Kirlin LLC', 11698, 765, 31);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Stoltenberg Group', 21417, 1069, 32);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Mann-Hahn', 19855, 2134, 33);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Hilll-Runolfsson', 10482, 363, 34);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Crooks and Sons', 20617, 480, 35);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Torphy-O''Conner', 570, 1057, 36);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Dickinson Inc', 20081, 2382, 37);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Bednar Group', 19717, 37, 38);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Reynolds-Armstrong', 24488, 63, 39);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Bogan, Raynor and Cremin', 8249, 2171, 40);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Weissnat, Harvey and Frami', 3010, 694, 41);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Johnson Inc', 7342, 709, 42);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Altenwerth-Willms', 13143, 1175, 43);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Cummings-Gulgowski', 24978, 1343, 44);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Waters-Runolfsson', 6245, 1915, 45);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Runolfsson-Mueller', 14306, 506, 46);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Mann, Kutch and Hilpert', 5807, 2314, 47);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Johns-Carroll', 14701, 341, 48);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Hegmann Group', 10616, 1089, 49);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Schowalter, Frami and Marquardt', 21103, 577, 50);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Kertzmann, Harris and Wilkinson', 226, 338, 51);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Kutch, Johnson and Gulgowski', 8514, 1646, 52);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Predovic Inc', 8692, 1014, 53);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Grady, Stiedemann and Murphy', 19182, 1842, 54);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Wilkinson Inc', 15677, 1272, 55);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Mayert, Kuvalis and Feeney', 1355, 1220, 56);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Hessel Group', 10897, 570, 57);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Bashirian-Terry', 265, 292, 58);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Cormier Group', 15354, 1980, 59);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Osinski and Sons', 17431, 1969, 60);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Schneider-Hegmann', 23843, 1604, 61);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Bartell, Kuhlman and Leannon', 2487, 1565, 62);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Legros-Waelchi', 23016, 1052, 63);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Ernser LLC', 13855, 1350, 64);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Bode-Runolfsson', 24494, 1007, 65);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Rowe Group', 4850, 608, 66);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Keebler LLC', 10769, 2214, 67);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Hermann, McCullough and King', 13995, 1338, 68);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Baumbach Group', 23878, 1762, 69);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Parisian, Hickle and Konopelski', 9018, 755, 70);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('O''Connell-Orn', 233, 1215, 71);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Kessler-Zulauf', 22210, 2469, 72);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Cronin, Ratke and McCullough', 9669, 1521, 73);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Robel Inc', 13120, 440, 74);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Harris and Sons', 19143, 1406, 75);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Fay, Shields and Kiehn', 15037, 1724, 76);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Kuhic LLC', 22824, 857, 77);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Reichert, Rohan and Haag', 17456, 2393, 78);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Purdy, Dare and Stamm', 5351, 1911, 79);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Christiansen-Connelly', 10899, 165, 80);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Bernier-Bernhard', 8016, 1342, 81);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Schiller, Kemmer and Haley', 1352, 285, 82);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Kuhn-Heathcote', 20091, 2033, 83);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Willms, Jerde and Treutel', 11229, 1269, 84);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Kerluke, Bergnaum and Heidenreich', 282, 2345, 85);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Rogahn LLC', 23734, 1137, 86);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Will and Sons', 10042, 1103, 87);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Weimann, Stracke and Shields', 23730, 2058, 88);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Spencer Group', 8103, 1364, 89);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Boyer-Robel', 24248, 1826, 90);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Schimmel LLC', 5133, 2359, 91);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Mertz, Stamm and Rath', 3531, 45, 92);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Fahey Group', 18897, 2405, 93);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Grimes, Shields and Williamson', 6326, 1915, 94);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Hoppe Inc', 8330, 894, 95);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Turcotte Inc', 23803, 593, 96);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Cummings-Sawayn', 12161, 804, 97);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Dietrich Inc', 14684, 274, 98);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Ryan-Parisian', 23440, 2495, 99);
insert into alimento (marca, presentacion, consumo_diario, id_mascota) values ('Frami-Nolan', 15773, 729, 100);
