insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Ferd', 'Botting', 'Treppas', 86224438, '9075 Union Parkway', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Agnola', 'Van Leijs', 'Houtby', 86198378, '086 Vahlen Street', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Caritta', 'Cockshutt', 'De Francesco', 88282702, '26 Hayes Center', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Audre', 'Laurentin', 'Deackes', 88624526, '081 Maryland Trail', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Burk', 'Diwell', 'Moverley', 80941337, '1387 Waxwing Street', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Christabel', 'Dulton', 'Mulroy', 83083126, '70 Jenifer Trail', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Hiram', 'Wattins', 'Goodayle', 86845686, '50 Moland Center', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Claudelle', 'Yukhnov', 'Chapelhow', 81300973, '42216 Knutson Alley', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Mendy', 'Milius', 'Eyree', 84836826, '812 Pine View Plaza', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Odetta', 'Manifield', 'Barrasse', 83794530, '80754 Larry Street', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Lock', 'Ropars', 'MacCourt', 80331007, '9675 Marquette Hill', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Hana', 'Gleadhell', 'Duffer', 84506101, '1371 Lawn Trail', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Riki', 'Pickaver', 'Jeaves', 80509587, '647 Pleasure Way', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Dionne', 'Jimmes', 'Gulston', 84909403, '28740 Hooker Way', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Matteo', 'McGunley', 'Gerry', 80967344, '12 Welch Center', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Randi', 'Hradsky', 'Spinozzi', 84021936, '225 Village Green Center', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Carly', 'MacMenamin', 'Doyland', 83775293, '81 Ruskin Junction', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Shermy', 'Stanett', 'Torbard', 82220242, '63 Mendota Park', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Minna', 'Ahrendsen', 'Curds', 83981068, '00 Petterle Avenue', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Cammi', 'Isakovic', 'Mariaud', 80680345, '7948 Gulseth Road', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Josepha', 'Denisovich', 'Blanchette', 84223893, '8824 Dorton Hill', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Evangelin', 'Rissen', 'Brotherwood', 80329223, '0788 Corscot Crossing', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Waly', 'McNiff', 'Kentish', 80381963, '5392 Clove Junction', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Raffarty', 'Stickels', 'Messier', 84970903, '125 Corben Plaza', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Doyle', 'Bagg', 'Lieb', 83980094, '35 Hallows Court', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Sonnie', 'Blackstone', 'Tait', 87853292, '0123 Autumn Leaf Plaza', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Karlik', 'Whitehair', 'Pond', 87250843, '32 Glendale Way', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Isabelita', 'Hazelgreave', 'Eakeley', 85793041, '27476 Birchwood Place', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Ailyn', 'Geater', 'Winterbottom', 84233208, '4 Nobel Hill', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Hester', 'Dulinty', 'Itzcak', 84991021, '91412 Montana Terrace', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Phyllida', 'Moxom', 'Thurlbeck', 82675755, '445 Scofield Circle', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Leodora', 'Crysell', 'Paliser', 85786620, '0314 Westend Point', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Juditha', 'Ickowics', 'Hadden', 83664766, '5993 Loftsgordon Plaza', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Cyb', 'McKeand', 'Huskisson', 86205252, '8100 Kinsman Terrace', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Julia', 'Reily', 'Bartoli', 81398429, '9531 Jana Road', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Cissiee', 'Kearsley', 'Weldrake', 85872876, '35 Logan Parkway', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Maisey', 'Colaton', 'Rohlfs', 84497104, '45691 Muir Place', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Nealy', 'Accum', 'Blesli', 83777418, '36780 Sherman Junction', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Werner', 'Desporte', 'McKoy', 81183781, '88 Carey Street', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Janelle', 'Standering', 'Ventam', 84180410, '892 Vera Way', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Jecho', 'Whear', 'Zisneros', 87845526, '96853 Fallview Trail', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Nessi', 'Simchenko', 'Kimmons', 85965979, '09600 Anzinger Hill', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Ardis', 'Aloshkin', 'Vowdon', 83075380, '8 Bayside Terrace', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Elisabetta', 'Townshend', 'Stennett', 88506370, '883 Scott Park', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Yasmeen', 'Tapton', 'Bracknell', 81817411, '0629 Scoville Park', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Gaylene', 'Brantzen', 'Escolme', 86366940, '868 Bartelt Park', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Felic', 'Orcott', 'Etheridge', 88156639, '6474 Aberg Circle', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Rici', 'Drife', 'Twigley', 85415831, '4048 Heffernan Point', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Gabby', 'Kollasch', 'Leverson', 87428870, '9 Northwestern Road', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Aili', 'Ferreras', 'Kilty', 83001312, '4026 Truax Court', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Marcos', 'Veque', 'Regan', 82318726, '327 3rd Drive', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Justinn', 'Jedrzej', 'Ruos', 81892025, '8 Northport Way', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Ronnie', 'Pfeuffer', 'Coleridge', 84401318, '786 Bayside Plaza', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Giffer', 'Rabbitts', 'Allatt', 86018494, '02 Bay Plaza', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Elvina', 'Cerro', 'Rummins', 81199583, '5 Dahle Junction', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('George', 'Gerardin', 'David', 80716024, '179 Holmberg Point', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Drona', 'Foston', 'Colenutt', 86718576, '7602 Nancy Point', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Teresita', 'Goodricke', 'Benediktovich', 81402630, '03 Towne Drive', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Stearn', 'Lightoller', 'Posvner', 81735698, '68561 Bay Place', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Tammie', 'Garnall', 'Von Helmholtz', 87995484, '9415 Kingsford Point', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Kristyn', 'Anthony', 'Pero', 81989710, '8 Village Green Way', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Woodman', 'Kattenhorn', 'Merrywether', 82424644, '4 Stone Corner Way', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Noella', 'Abramski', 'Donnersberg', 80811183, '1 Utah Hill', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Shellysheldon', 'Deniseau', 'Mansion', 86818594, '521 Oakridge Circle', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Arielle', 'Annesley', 'Gilfoyle', 80647874, '42152 Iowa Point', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Kurtis', 'Pettifor', 'Tomenson', 86253794, '082 Parkside Trail', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Rog', 'Ellse', 'Reilly', 87832172, '4 Lukken Pass', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Tim', 'Colgrave', 'Mewburn', 87649475, '17 Goodland Hill', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Augusto', 'Joseph', 'Ower', 84661843, '8 5th Center', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Demetra', 'Josefsen', 'McKechnie', 85644788, '4641 Hoffman Hill', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Neill', 'Phipson', 'Laity', 88624453, '9 Schurz Center', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Kikelia', 'Flannigan', 'Corzor', 86779132, '36 Burrows Plaza', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Brnaby', 'Saker', 'Werner', 80075831, '4 Eagle Crest Parkway', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Lewes', 'Kadar', 'Burthom', 81609142, '30897 Sage Center', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Kary', 'Guthrie', 'Grinnell', 83005586, '4 Di Loreto Alley', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Willabella', 'McCuthais', 'Wyles', 87123832, '2975 Moland Pass', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Kay', 'Tomlinson', 'Ginsie', 84313307, '23 Oak Center', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Maggee', 'Fitzpayn', 'Kacheller', 85178435, '07372 Roth Terrace', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Normie', 'Alliberton', 'Lambarton', 87463276, '05922 Chinook Court', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Kimmy', 'Pietersma', 'Kyteley', 88493053, '34579 Nancy Road', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Debbie', 'Piolli', 'Mabbott', 84054630, '5 Esch Junction', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Linea', 'Dauber', 'Phayre', 81149900, '7 Kensington Center', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Linnie', 'Babber', 'Losseljong', 86682245, '54044 Dexter Drive', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Earvin', 'Mauchlen', 'Keaveney', 85238049, '4 Oak Way', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Nanette', 'Wonfor', 'Leist', 82045700, '65 Manitowish Lane', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Alethea', 'Ham', 'Haughan', 88572322, '4644 American Ash Court', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Ofella', 'Sabattier', 'Mila', 80323412, '19436 Gerald Street', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Celisse', 'Monckman', 'Gloster', 86417549, '26 Harbort Street', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Brooks', 'Dudley', 'Tout', 86585521, '8 Scoville Park', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Kari', 'Rany', 'Franken', 80926379, '8538 Superior Center', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Andrew', 'Antyukhin', 'Capun', 82697242, '6 Sugar Avenue', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Annabell', 'Biaggioli', 'Shearman', 86132685, '804 Florence Drive', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Stacia', 'Cleave', 'Fancet', 88531020, '9 Burrows Street', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Yorgos', 'Worland', 'Lomis', 81061928, '6087 Springview Court', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Nara', 'Spellar', 'Geraghty', 87131887, '32 Hagan Way', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Marji', 'Quantrell', 'Kos', 88058454, '8087 Towne Point', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Elvis', 'Berthelmot', 'Dwelley', 88676799, '7064 North Parkway', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Bronnie', 'Bubbings', 'Kershow', 85353092, '60956 Elmside Circle', false);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Persis', 'Tofpik', 'Parkin', 82243585, '8 Springview Lane', true);
insert into cliente (nombre, primer_apellido, segundo_apellido, telefono, direccion_entrega, notificacion) values ('Joyous', 'Iczokvitz', 'Gilffillan', 84123989, '2923 Butternut Drive', true);
