insert into mascota (nombre, raza, especie , id_cliente) values ('Skyler', 'Turaco, violet-crested', 'Tauraco porphyrelophus', 1);
insert into mascota (nombre, raza, especie , id_cliente) values ('Dudley', 'Deer, spotted', 'Axis axis', 2);
insert into mascota (nombre, raza, especie , id_cliente) values ('Maura', 'Capybara', 'Hydrochoerus hydrochaeris', 3);
insert into mascota (nombre, raza, especie , id_cliente) values ('Rachel', 'Dove, laughing', 'Streptopelia senegalensis', 4);
insert into mascota (nombre, raza, especie , id_cliente) values ('Shea', 'Heron, giant', 'Ardea golieth', 5);
insert into mascota (nombre, raza, especie , id_cliente) values ('Alleen', 'Sheathbill, snowy', 'Chionis alba', 6);
insert into mascota (nombre, raza, especie , id_cliente) values ('Madel', 'Kingfisher, pied', 'Ceryle rudis', 7);
insert into mascota (nombre, raza, especie , id_cliente) values ('Matthias', 'Cape fox', 'Vulpes chama', 8);
insert into mascota (nombre, raza, especie , id_cliente) values ('Webb', 'Coqui francolin', 'Francolinus coqui', 9);
insert into mascota (nombre, raza, especie , id_cliente) values ('Salome', 'Richardson''s ground squirrel', 'Spermophilus richardsonii', 10);
insert into mascota (nombre, raza, especie , id_cliente) values ('Jervis', 'Pademelon, red-legged', 'Thylogale stigmatica', 11);
insert into mascota (nombre, raza, especie , id_cliente) values ('Wat', 'Scarlet macaw', 'Ara macao', 12);
insert into mascota (nombre, raza, especie , id_cliente) values ('Agnes', 'Violet-eared waxbill', 'Uraeginthus granatina', 13);
insert into mascota (nombre, raza, especie , id_cliente) values ('Sol', 'Pintail, bahama', 'Anas bahamensis', 14);
insert into mascota (nombre, raza, especie , id_cliente) values ('Orrin', 'Cormorant, little', 'Phalacrocorax niger', 15);
insert into mascota (nombre, raza, especie , id_cliente) values ('Thatch', 'Bat, asian false vampire', 'Megaderma spasma', 16);
insert into mascota (nombre, raza, especie , id_cliente) values ('Marchall', 'Crane, stanley', 'Anthropoides paradisea', 17);
insert into mascota (nombre, raza, especie , id_cliente) values ('Florida', 'Lizard, blue-tongued', 'Tiliqua scincoides', 18);
insert into mascota (nombre, raza, especie , id_cliente) values ('Jessalyn', 'Waved albatross', 'Diomedea irrorata', 19);
insert into mascota (nombre, raza, especie , id_cliente) values ('Ahmed', 'Red sheep', 'Ovis ammon', 20);
insert into mascota (nombre, raza, especie , id_cliente) values ('Corty', 'Native cat', 'Dasyurus viverrinus', 21);
insert into mascota (nombre, raza, especie , id_cliente) values ('Sharlene', 'Crab, sally lightfoot', 'Graspus graspus', 22);
insert into mascota (nombre, raza, especie , id_cliente) values ('Oona', 'Magnificent frigate bird', 'Fregata magnificans', 23);
insert into mascota (nombre, raza, especie , id_cliente) values ('Nariko', 'Ring-tailed gecko', 'Cyrtodactylus louisiadensis', 24);
insert into mascota (nombre, raza, especie , id_cliente) values ('Hodge', 'Common seal', 'Phoca vitulina', 25);
insert into mascota (nombre, raza, especie , id_cliente) values ('Danny', 'Dog, african wild', 'Lycaon pictus', 26);
insert into mascota (nombre, raza, especie , id_cliente) values ('Noni', 'Snake, buttermilk', 'Coluber constrictor', 27);
insert into mascota (nombre, raza, especie , id_cliente) values ('Igor', 'Magistrate black colobus', 'Colobus guerza', 28);
insert into mascota (nombre, raza, especie , id_cliente) values ('Hester', 'Monster, gila', 'Heloderma horridum', 29);
insert into mascota (nombre, raza, especie , id_cliente) values ('Padraic', 'Harbor seal', 'Phoca vitulina', 30);
insert into mascota (nombre, raza, especie , id_cliente) values ('Chloette', 'Asiatic jackal', 'Canis aureus', 31);
insert into mascota (nombre, raza, especie , id_cliente) values ('Windy', 'Mallard', 'Anas platyrhynchos', 32);
insert into mascota (nombre, raza, especie , id_cliente) values ('Winna', 'Dragon, netted rock', 'Ctenophorus ornatus', 33);
insert into mascota (nombre, raza, especie , id_cliente) values ('Hartwell', 'Swallow-tail gull', 'Creagrus furcatus', 34);
insert into mascota (nombre, raza, especie , id_cliente) values ('Melicent', 'White-fronted capuchin', 'Cebus albifrons', 35);
insert into mascota (nombre, raza, especie , id_cliente) values ('Gris', 'Swainson''s francolin', 'Francolinus swainsonii', 36);
insert into mascota (nombre, raza, especie , id_cliente) values ('Waylan', 'Macaw, scarlet', 'Ara macao', 37);
insert into mascota (nombre, raza, especie , id_cliente) values ('Melodee', 'Black-capped capuchin', 'Cebus apella', 38);
insert into mascota (nombre, raza, especie , id_cliente) values ('Early', 'Turkey, australian brush', 'Alectura lathami', 39);
insert into mascota (nombre, raza, especie , id_cliente) values ('Amalle', 'Burrowing owl', 'Speotyte cuniculata', 40);
insert into mascota (nombre, raza, especie , id_cliente) values ('Bran', 'Goose, canada', 'Branta canadensis', 41);
insert into mascota (nombre, raza, especie , id_cliente) values ('Willabella', 'Water moccasin', 'Agkistrodon piscivorus', 42);
insert into mascota (nombre, raza, especie , id_cliente) values ('Rooney', 'Gull, lava', 'Larus fuliginosus', 43);
insert into mascota (nombre, raza, especie , id_cliente) values ('Ambrosi', 'Eastern diamondback rattlesnake', 'Crotalus adamanteus', 44);
insert into mascota (nombre, raza, especie , id_cliente) values ('Candace', 'Gecko, bent-toed', 'Cyrtodactylus louisiadensis', 45);
insert into mascota (nombre, raza, especie , id_cliente) values ('Dyan', 'Goat, mountain', 'Oreamnos americanus', 46);
insert into mascota (nombre, raza, especie , id_cliente) values ('Annmaria', 'Kingfisher, pied', 'Ceryle rudis', 47);
insert into mascota (nombre, raza, especie , id_cliente) values ('Ferdinande', 'Stork, woolly-necked', 'Ciconia episcopus', 48);
insert into mascota (nombre, raza, especie , id_cliente) values ('Chantal', 'Kirk''s dik dik', 'Madoqua kirkii', 49);
insert into mascota (nombre, raza, especie , id_cliente) values ('Marlee', 'Hen, sage', 'Centrocercus urophasianus', 50);
insert into mascota (nombre, raza, especie , id_cliente) values ('Perrine', 'Macaque, bonnet', 'Macaca radiata', 51);
insert into mascota (nombre, raza, especie , id_cliente) values ('Merline', 'Gull, swallow-tail', 'Creagrus furcatus', 52);
insert into mascota (nombre, raza, especie , id_cliente) values ('Gilberta', 'European stork', 'Ciconia ciconia', 53);
insert into mascota (nombre, raza, especie , id_cliente) values ('Garvy', 'Black vulture', 'Aegypius tracheliotus', 54);
insert into mascota (nombre, raza, especie , id_cliente) values ('Gertruda', 'Dark-winged trumpeter', 'Psophia viridis', 55);
insert into mascota (nombre, raza, especie , id_cliente) values ('Isabeau', 'Parrot, hawk-headed', 'Deroptyus accipitrinus', 56);
insert into mascota (nombre, raza, especie , id_cliente) values ('Winny', 'Yellow-bellied marmot', 'Marmota flaviventris', 57);
insert into mascota (nombre, raza, especie , id_cliente) values ('Herve', 'Eagle, tawny', 'Anitibyx armatus', 58);
insert into mascota (nombre, raza, especie , id_cliente) values ('Felita', 'Skunk, striped', 'Mephitis mephitis', 59);
insert into mascota (nombre, raza, especie , id_cliente) values ('Kaela', 'Hornbill, leadbeateri''s ground', 'Bucorvus leadbeateri', 60);
insert into mascota (nombre, raza, especie , id_cliente) values ('Thurston', 'Tortoise, indian star', 'Geochelone elegans', 61);
insert into mascota (nombre, raza, especie , id_cliente) values ('Orland', 'Australian magpie', 'Gymnorhina tibicen', 62);
insert into mascota (nombre, raza, especie , id_cliente) values ('Wald', 'Red-headed woodpecker', 'Melanerpes erythrocephalus', 63);
insert into mascota (nombre, raza, especie , id_cliente) values ('Janet', 'Dabchick', 'Tachybaptus ruficollis', 64);
insert into mascota (nombre, raza, especie , id_cliente) values ('Kenyon', 'Crimson-breasted shrike', 'Laniaurius atrococcineus', 65);
insert into mascota (nombre, raza, especie , id_cliente) values ('Melania', 'Red phalarope', 'Phalaropus fulicarius', 66);
insert into mascota (nombre, raza, especie , id_cliente) values ('Lockwood', 'Duiker, common', 'Sylvicapra grimma', 67);
insert into mascota (nombre, raza, especie , id_cliente) values ('Tyne', 'Monitor, white-throated', 'Varanus albigularis', 68);
insert into mascota (nombre, raza, especie , id_cliente) values ('Gav', 'Armadillo, seven-banded', 'Dasypus septemcincus', 69);
insert into mascota (nombre, raza, especie , id_cliente) values ('Stacy', 'Grey heron', 'Ardea cinerea', 70);
insert into mascota (nombre, raza, especie , id_cliente) values ('Jen', 'Chuckwalla', 'Sauromalus obesus', 71);
insert into mascota (nombre, raza, especie , id_cliente) values ('Jobina', 'White-throated robin', 'Irania gutteralis', 72);
insert into mascota (nombre, raza, especie , id_cliente) values ('Alidia', 'Coatimundi, ring-tailed', 'Nasua nasua', 73);
insert into mascota (nombre, raza, especie , id_cliente) values ('Risa', 'Whip-tailed wallaby', 'Macropus parryi', 74);
insert into mascota (nombre, raza, especie , id_cliente) values ('Lydia', 'Red deer', 'Cervus elaphus', 75);
insert into mascota (nombre, raza, especie , id_cliente) values ('Estell', 'Robin, kalahari scrub', 'Certotrichas paena', 76);
insert into mascota (nombre, raza, especie , id_cliente) values ('Orbadiah', 'Galah', 'Eolophus roseicapillus', 77);
insert into mascota (nombre, raza, especie , id_cliente) values ('Fleur', 'Grouse, greater sage', 'Centrocercus urophasianus', 78);
insert into mascota (nombre, raza, especie , id_cliente) values ('Avery', 'Western lowland gorilla', 'Gorilla gorilla', 79);
insert into mascota (nombre, raza, especie , id_cliente) values ('Melany', 'Australian sea lion', 'Neophoca cinerea', 80);
insert into mascota (nombre, raza, especie , id_cliente) values ('Izak', 'Paradoxure', 'Paradoxurus hermaphroditus', 81);
insert into mascota (nombre, raza, especie , id_cliente) values ('Pammy', 'Bat-eared fox', 'Otocyon megalotis', 82);
insert into mascota (nombre, raza, especie , id_cliente) values ('Chrotoem', 'Jackal, asiatic', 'Canis aureus', 83);
insert into mascota (nombre, raza, especie , id_cliente) values ('Rosabel', 'Bushbuck', 'Tragelaphus scriptus', 84);
insert into mascota (nombre, raza, especie , id_cliente) values ('Lock', 'Whale, long-finned pilot', 'Globicephala melas', 85);
insert into mascota (nombre, raza, especie , id_cliente) values ('Ester', 'Goose, greylag', 'Anser anser', 86);
insert into mascota (nombre, raza, especie , id_cliente) values ('Analise', 'Tawny eagle', 'Anitibyx armatus', 87);
insert into mascota (nombre, raza, especie , id_cliente) values ('Garvy', 'Tailless tenrec', 'Tenrec ecaudatus', 88);
insert into mascota (nombre, raza, especie , id_cliente) values ('Maegan', 'Moose', 'Alces alces', 89);
insert into mascota (nombre, raza, especie , id_cliente) values ('Mahalia', 'Jacana, african', 'Actophilornis africanus', 90);
insert into mascota (nombre, raza, especie , id_cliente) values ('Veda', 'Jackal, black-backed', 'Canis mesomelas', 91);
insert into mascota (nombre, raza, especie , id_cliente) values ('Zonnya', 'Robin, kalahari scrub', 'Certotrichas paena', 92);
insert into mascota (nombre, raza, especie , id_cliente) values ('Glenn', 'Swan, black', 'Cygnus atratus', 93);
insert into mascota (nombre, raza, especie , id_cliente) values ('Elana', 'Glossy ibis', 'Plegadis falcinellus', 94);
insert into mascota (nombre, raza, especie , id_cliente) values ('Sela', 'Vulture, lappet-faced', 'Aegypius tracheliotus', 95);
insert into mascota (nombre, raza, especie , id_cliente) values ('Merry', 'Coke''s hartebeest', 'Alcelaphus buselaphus cokii', 96);
insert into mascota (nombre, raza, especie , id_cliente) values ('Frederigo', 'Collared peccary', 'Tayassu tajacu', 97);
insert into mascota (nombre, raza, especie , id_cliente) values ('Sileas', 'Australian sea lion', 'Neophoca cinerea', 98);
insert into mascota (nombre, raza, especie , id_cliente) values ('Franni', 'Monitor, white-throated', 'Varanus albigularis', 99);
insert into mascota (nombre, raza, especie , id_cliente) values ('Amalle', 'Crowned hawk-eagle', 'Spizaetus coronatus', 100);
